source "https://rubygems.org"

gem "jekyll", "~> 3.5"

gem "jekyll-default-layout", "~> 0.1"
gem "jekyll-feed", "~> 0.9"
gem "jekyll-optional-front-matter", "~> 0.2"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-redirect-from", "~> 0.12"
gem "jekyll-relative-links", "~> 0.4"
gem "jekyll-sitemap", "~> 1.0"

gem "classifier-reborn", "~> 2.1"

source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']